config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: [:index, :edit, :update] 
  put '/make_admin/:id' , to:'users#make_admin'
  put '/cancel_admin/:id' , to:'users#cancel_admin_rights'
  get '/users/:id' , to:'users#show'
  get '/news/:category', to:'articles#index', as: 'articles_by_category'
  root :to => "articles#index", :category => 'all'
  post '/preferences' , to: 'preferences#create', as: 'preference_create'
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  get '/search' => 'articles#search', :as => 'search_article'
end

app/models/article.rb
class Article < ApplicationRecord
  CATEGORY_MAP = { people: 1, opinions: 2, auto: 3, technologies: 4, realt: 5 }.freeze
  RUSSION_CATEGORY_MAP = { 1 => 'Люди', 2 => 'Мнения', 3 => 'Авто', 4 => 'Технологии', 5 => 'Недвижимость' }.freeze
  PER_PAGE = 14
  has_one_attached :image
  validates :title, presence: { message: 'Укажите название' }
  validates :image, presence: { message: 'Прикрепите фото/картинку' }
  validates :text, presence:  { message: 'Напишите текст' }
  belongs_to :category
  belongs_to :admin
  has_many :comments, as: :commentable, dependent: :delete_all
  MONTH_MAP = {
    1 => 'января',
    2 => 'февраля',
    3 => 'марта',
    4 => 'апреля',
    5 => 'мая',
    6 => 'июня',
    7 => 'июля',
    8 => 'августа',
    9 => 'сентября',
    10 => 'октября',
    11 => 'декабря',
    12 => 'декабря'
  }.freeze

  def parse_date
    date = created_at
    now = Time.zone.now.strftime('%d-%m')
    if date.strftime('%d-%m') == now
      "Сегодня в #{date.strftime('%H:%M')}"
    else
      "#{date.day} #{Article::MONTH_MAP[date.month]} #{Article::MONTH_MAP[date.year]} в #{date.strftime('%H:%M')}"
    end
  end

  def category_russian_name
    Article::RUSSION_CATEGORY_MAP[category_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authentication, only: %i[index show search]
  before_action :check_admin, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = find_articles
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to(action: 'show', id: @article)
    else
      flash[:alert] = 'Данные заполнены неверно, попробуйте ещё раз'
      render('new')
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to(action: 'show', id: @article)
    else
      flash[:alert] = 'Данные заполнены неверно, попробуйте ещё раз'
      redirect_to(action: 'edit')
    end
  end

  def destroy
    @article.destroy!
    redirect_to(root_path)
  end

  def search
    @articles = Article.where('title ILIKE ? ', "%#{params[:search]}%")
    flash[:error] = 'Ничего не найдено' if @articles.empty?
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    parameters = params.require(:article).permit(:title, :text, :image)
    parameters[:category_id] = Article::CATEGORY_MAP[params[:article][:category].to_sym] if params[:article][:category]
    parameters[:admin_id] = current_user.id
    parameters
  end

  def find_articles
    if Article::CATEGORY_MAP.include?(params[:category].to_sym)
      Article.where(category_id: Article::CATEGORY_MAP[params[:category].to_sym]).order(created_at: :desc).paginate(
        page: params[:page],
        per_page: Article::PER_PAGE
      )
    else
      select_atricles_by_category
    end
  end

  def select_atricles_by_category
    all_articles = Article.all.order(created_at: :desc).to_a
    articles = []
    Article::CATEGORY_MAP.each_pair do |_key, value|
      articles << all_articles.select { |article| article.category_id == value }[0..9]
    end
    articles
  end
end

app/views/articles/_all_news.html.erb
<div class="news-wrapper">
  <div class="container-x d-flex mb-3">
    <div class="row">
      <% @articles.flatten.shuffle[0..11].each do |article| %> 
        <div class="col-sm-3 box2">  
          <div class="img-wrap">
            <div class="img-wrap-bright ">
              <a href="<%= article_path(article.id)%>">
                <div  class="div-news-title">
                  <img  src="<%= rails_blob_url(article.image) %>"width="348" height="170">
                </div>
              </a>
            </div>
            <a href="" class="tile-section"><%=article.category_russian_name%></a>
            <a href="" class="b-tile-comments"><b><span><%= article.comments.count%></span></b></a>
            <h5><b><%= link_to "#{article.title}", article_path(article.id), class: "text-white"%><span></b></h5>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row ">
      <div class="col-md-12 mb-2">
        <div class="news-category-title"><%= link_to "ЛЮДИ", '/news/people', class: "text-dark"%></div>
      </div>
    </div>
  </div>
  <% people = @articles[0] %> 
  <%if (people.size >=10 )%>
    <div class="container-x d-flex mb-3">
      <div class="row">
        <%= render partial: "line_articles_to_category",object: people[0..4], as: 'articles' %>
      </div>
    </div>
    <div class="container-x d-flex">
      <div class="row my-2 mx-2">
        <% people[5..6].each_with_index do |article,index| %> 
          <%if index == 0 %>
            <%= render partial: "wide_article",object: article, as: 'article'%>
          <%end%>
          <%if index == 1 %>
            <%= render partial: "narrow_article",object: article, as: 'article'%>
          <%end%>
        <%end%>
        <div class="custom-col-news mb-2">  
            <%= render partial: "column_articles",object: people[7..9], as: 'articles'%>
        </div>
        <div class="col-md-12 mt-3">  
          <div class="horisontal_gray_line mt-3"></div>
        </div>
      </div>    
    </div>
    <div class="col-md-12 mb-3">  
      <a href="/news/people" class="footer-button">Все новости о людях</a>
    </div>
  <%end%>
  <div class="container-fluid">
    <div class="row ">
      <div class="col-md-12 mb-2">
        <div class="news-category-title"><%= link_to "Мнения", '/news/opinions', class: "text-dark"%></div>
      </div>
    </div>
  </div>
  <% opinions = @articles[1] %> 
  <%if (people.size >=4 )%>
    <div class="container-x d-flex mb-3">
      <div class="row">
        <%opinions[0..3].each do |article| %> 
          <div class="col-sm-3 box2">  
            <div class="img-wrap">
              <div class="img-wrap-bright ">
                <a href="<%= article_path(article.id)%>">
                  <div  class="div-news-title">
                    <img  src="<%= rails_blob_url(article.image) %>", padding ="58px 25px 5px" , height="200">
                  </div>
                </a>
              </div>
              <a href="" class="tile-section"><%=article.category_russian_name%></a>
              <a href="" class="b-tile-comments"><b><span>0</span></b></a>
              <h5><b><%= link_to "#{article.title}", article_path(article.id), class: "text-white"%><span></b></h5>
            </div>
          </div>
        <%end%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 my-4">  
        <a href="/news/opinions" class="footer-button">Все мнения</a>
      </div>
    </div>
  <%end%>
  <div class="container-fluid">
    <div class="row ">
      <div class="col-md-12 mb-2">
        <div class="news-category-title"><%= link_to "Авто", '/news/auto', class: "text-dark"%></div>
      </div>
    </div>
  </div> 
  <% auto = @articles[2] %> 
  <%if (auto.size >=10 )%>
    <div class="container-x d-flex mb-3">
      <div class="row">
        <%= render partial: "line_articles_to_category",object: auto[0..4], as: 'articles'%>
      </div>
    </div>
    <div class="container-x d-flex">
      <div class="row my-2 mx-2">
        <% auto[5..6].each_with_index do |article,index| %> 
          <%if index == 0 %>
          <%= render partial: "narrow_article",object: article, as: 'article'%>
          <%end%>
          <%if index == 1 %>
          <%= render partial: "wide_article",object: article, as: 'article'%>
          <%end%>
        <%end%>
        <div class="custom-col-news mb-2">  
          <%= render partial: "column_articles",object: auto[7..9], as: 'articles'%>
        </div>
        <div class="col-md-12 mt-3">  
          <div class="horisontal_gray_line mt-3"></div>
        </div>
      </div>    
    </div>
    <div class="col-md-12 mb-3">  
      <a href="/news/auto" class="footer-button">Все новости об автомобилях</a>
    </div>
  <%end%>
  <div class="container-fluid">
    <div class="row ">
      <div class="col-md-12 mb-2">
        <div class="news-category-title"><%= link_to "Технологии", '/news/technologies', class: "text-dark"%></div>
      </div>
    </div>
  </div> 
  <% technologies = @articles[3]%> 
  <%if (technologies.size >=10 )%>
    <div class="container-x d-flex mb-3">
      <div class="row">
        <%= render partial: "line_articles_to_category",object: technologies [0..4], as: 'articles'%>
      </div>
    </div>
    <div class="container-x d-flex">
      <div class="row my-2 mx-2">
        <% technologies[5..6].each_with_index do |article,index| %> 
          <%if index == 0 %>
            <%= render partial: "wide_article",object: article, as: 'article'%>
          <%end%>
          <%if index == 1 %>
            <%= render partial: "narrow_article",object: article, as: 'article'%>
          <%end%>
        <%end%>
        <div class="custom-col-news mb-2">  
          <%= render partial: "column_articles",object: technologies[7..9], as: 'articles'%>
        </div>
        <div class="col-md-12 mt-3">  
          <div class="horisontal_gray_line mt-3"></div>
        </div>
      </div>    
    </div>
    <div class="col-md-12 mb-3">  
      <a href="/news/technologies" class="footer-button">Все новости о технологиях</a>
    </div>
  <%end%>
  <div class="container-fluid">
    <div class="row ">
      <div class="col-md-12 mb-2">
        <div class="news-category-title"><%= link_to "Недвижимость", '/news/realt', class: "text-dark"%></div>
      </div>
    </div>
  </div> 
  <% realt = @articles[4] %> 
  <%if (realt.size >=10 )%>
    <div class="container-x d-flex mb-3">
      <div class="row">
        <%= render partial: "line_articles_to_category",object: realt[0..4], as: 'articles'%>
      </div>
    </div>
    <div class="container-x d-flex">
      <div class="row my-2 mx-2">
        <% realt[5..6].each_with_index do |article,index| %> 
          <%if index == 0 %>
            <%= render partial: "narrow_article",object: article, as: 'article'%>
          <%end%>
          <%if index == 1 %>
            <%= render partial: "wide_article",object: article, as: 'article'%>
          <%end%>
        <%end%>
        <div class="custom-col-news mb-2">  
            <%= render partial: "column_articles",object: realt[7..9], as: 'articles'%>
        </div>
        <div class="col-md-12 mt-3">  
          <div class="horisontal_gray_line mt-3"></div>
        </div>
      </div>    
    </div>
    <div class="col-md-12 mb-3">  
      <a href="/news/realt" class="footer-button">Все новости о недвижимости</a>
    </div>
  <%end%>
</div>  

app/views/articles/_article.html.erb
<div class="col-md-4 mb-2">  
  <div class="card border-0 ">   
    <img class="card-img-top" src="<%= rails_blob_url(article.image) %>" height="200">
    <div class="card-body">
      <div class="news-tidings__clamping">
        <div class="news-tidings__subtitle">
          <h5 class="card-title"><a><b><%= link_to "#{article.title}", article_path(article.id) %></b></a></h5>
        </div>
        <div class="news-tidings__speech news-helpers_hide_mobile-small">
          <div class="card-text"><%= simple_format(article.text.truncate(270)) %></div>
        </div>
      </div>
      <%= render partial: "comment_and_date",object: article, as: 'article'%>
    </div>
  </div>
</div>

app/views/articles/_article_more.html.erb
<div class="container d-flex">
  <div class="row my-2 mx-2 mt-5">
   <%= render @articles %> 
  </div>
</div>

app/views/articles/_column_articles.html.erb
<% articles.each_with_index do |article,index| %> 
  <div class="row  <%='mb-3' if index == 0 %> <%='my-3' if index == 1 %> <%='mt-3' if index == 2 %> ">
    <div class="col-7">
      <a href="<%= article_path(article.id)%>">
        <img class="small-news"src="<%= rails_blob_url(article.image) %>" width="250" height="120">
      </a>
    </div>
    <div class="col-5">
      <div class="row">
        <div class="news-tidings__subtitle">
          <h5 class="card-title"><b><a><%= link_to "#{article.title}", article_path(article.id) %></b></a></h5>
        </div>
      </div>
      <div class="row">
        <%= render partial: "comment_and_date",object: article, as: 'article'%>
      </div>
    </div>
  </div>  
  <%unless index==2%><div class="horisontal_gray_line "></div><%end%>
<%end%> 

app/views/articles/_comment.html.erb
<div class="row">
  <div class="column">
  <%=  image_tag("noavatar.png",class: "img-fluid rounded-circle")%>
  </div>
    <div class="column2">
      <div class="row">
        <div class="col-md-8">
          <b> <%=comment.user_id  %></b>
        </div>
            <% if @user %>
              <% like = comment.liked?(comment.id,@user.id) %>
                <% if like %>
                  <div class="col-md-1">
                    <div class="like-count"> <%= comment.likes.size %>
                      <%= link_to image_tag("like-alert.png", size: "15"), preference_create_path(comment_id: comment.id, user_id: @user.id, type: "Like", article_id: comment.article_id), method: :post, remote: true%>
                    </div>
                  </div>
                  <div class="col-md-1">
                    <div class="dislike-count"> <%= comment.dislikes.size %>
                      <%= link_to image_tag("dislike.png", size: "15"), preference_create_path(comment_id: comment.id, user_id: @user.id,type: "Dislike", article_id: comment.article_id), method: :post, remote: true %>
                    </div>
                  </div>
                <% elsif like == false %>
                  <div class="col-md-1">
                    <div class="like-count"> <%= comment.likes.size %>
                      <%= link_to image_tag("like.png", size: "15"),preference_create_path(comment_id: comment.id, user_id: @user.id, type: "Like", article_id: comment.article_id),method: :post , remote: true%>
                    </div>
                  </div>
                  <div class="col-md-1">
                    <div class="dislike-count"> <%= comment.dislikes.size%>
                      <%= link_to image_tag("dislike-alert.png", size: "15"), preference_create_path(comment_id: comment.id, user_id: @user.id,type: "Dislike", article_id: comment.article_id), method: :post, remote: true %>
                    </div>
                  </div>
                <% else %>
                  <div class="col-md-1">
                    <div class="like-count"> <%= comment.likes.size %>
                      <%= link_to image_tag("like.png", size: "15"),preference_create_path(comment_id: comment.id, user_id: @user.id, type: "Like", article_id: comment.article_id), method: :post, remote: true%>
                    </div>
                  </div>
                  <div class="col-md-1">
                    <div class="dislike-count"> <%= comment.dislikes.size %>
                      <%= link_to image_tag("dislike.png", size: "15"), preference_create_path(comment_id: comment.id, user_id: @user.id,type: "Dislike", article_id: comment.article_id), method: :post, remote: true %>
                    </div>
                  </div>
                <% end %>
              <%else%>
                <div class="col-md-1">
                  <div class="like-count"> <%= comment.likes.size %>
                    <%= link_to image_tag("like.png", size: "15"), preference_create_path(), method: :post, remote: true%>
                  </div>
                </div>
                <div class="col-md-1">
                  <div class="dislike-count"> <%= comment.dislikes.size %>
                    <%= link_to image_tag("dislike.png", size: "15"), preference_create_path(), method: :post, remote: true %>
                  </div>
                </div>
            <% end %> 
      </div>
      <div class="row">
        <div class="col-md-6">
          <p><%= comment.content %></p>
        </div> 
      </div>
      <div class="row">
        <div class="response_comment">
          <% id_comment = comment.id %>
          <p onclick="stateChange(<%= id_comment %>)">Ответить</p>
        </div>
      </div>
    </div>        
  <div id = <%= id_comment %> style="display:none">
    <div class="row mb-4">
      <div class="col-md-6 offset-md-1 " style="background-clor:red">
      <%= form_for :comment, url: "/comments/#{comment.id}/comments/", method: :post do |f| %>
      <%= f.hidden_field :article_id,  value: @article.id %>
      <%= f.text_area :content,class: "form-control" , placeholder: "Ответ для #{comment.user_id}" %><br/>
        <div class="col-md-6">
          <%= f.submit "Высказаться" , :class => "auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

  <% if comment.commentable_type == "Article" %>
    <ul><%= render partial: 'comment', collection: comment.comments %></ul>  
  <% else %>
  <%= render partial: 'comment', collection: comment.comments %> 
  <% end %>
<script>
function stateChange(id_comment) {
  var obj = document.getElementById(id_comment);
  obj.style.display = 
      (obj.style.display == "none" ?
      "block" : "none");
}
</script>

app/views/articles/_comment_and_date.html.erb
<div class="news-tidings__detail">
<div class="news-tidings__control">
  <div class="news-tidings__group">
    <div class="news-tidings__comment">0</div>
  </div>
  <div class="news-tidings__time">
    <%= article.parse_date%>  
   </div>
</div>
</div>

app/views/articles/_line_articles_to_category.html.erb
<% articles.each do |article| %>  
  <div class="custom-col-2 box2-small">  
    <div class="img-wrap-small">
      <div class="img-wrap-small-bright ">
        <a href="<%= article_path(article.id)%>">
          <div  class="div-news-title-small">
            <img  src="<%= rails_blob_url(article.image) %>"width="278" height="100">
          </div>
        </a>
      </div>
      <h5><b><%= link_to "#{article.title}", article_path(article.id), class: "text-white"%><span></b></h5>
    </div>
  </div>
<%end%>

app/views/articles/_narrow_article.html.erb
<div class="col-md-3 mb-2">  
  <div class="vertical_gray_line">
    <div class="card border-0 ml-1 mr-3">   
      <a href="<%= article_path(article.id)%>">
        <img class="card-img-top" src="<%= rails_blob_url(article.image) %>" height="150">
      </a>
      <div class="card-body">
        <div class="news-tidings__subtitle">
          <h5 class="card-title"><b><a><%= link_to "#{article.title}", article_path(article.id) %></b></a></h5>
        </div>
        <div class="news-tidings__speech news-helpers_hide_mobile-small">
          <div class="card-text"><%= simple_format(article.text.truncate(240)) %></div>
        </div>
        <%= render partial: "comment_and_date",object: article, as: 'article'%>
      </div>
    </div>
  </div>
</div>

app/views/articles/_news_to_category.html.erb
<div class="news-wrapper">
<% unless params[:category]=='opinions'%>
  <div class="container-x d-flex mb-3">
    <div class="row">
      <% @articles.limit(8).each do |article| %> 
        <div class="col-sm-3 box2">  
            <div class="img-wrap">
              <div class="img-wrap-bright ">
              <a href="<%= article_path(article.id)%>"><div  class="div2">
                <div  class="div-news-title">
                  <img  src="<%= rails_blob_url(article.image) %>"width="348" height="170">
                </div>  
              </div></a>
              </div>
              <div class ="comments">
                <a href="" class="button-style button-style_adscititious button-style_small news-header__button news-header__button_comments" id="news-header-comments-counter"> <%= article.comments.count%></a>
              </div>
                <h5><b><%= link_to "#{article.title}", article_path(article.id), class: "text-white"%></b></h5>
            </div>
        </div>
      <%end%>
    </div>
  </div>
  
  <div class="container">
    <div class="row ">
      <div class="col-md-8 ml-5">
        <h5>Все новости:</h5>
      </div>
    </div>
  </div>
  <hr />
  <%if (@articles.size >=8 )%>
  <div id="articles">
  <div class="container d-flex">
    <div class="row my-2 mx-2 mt-5">
        <%= render @articles[8..-1] %>
      </div>
    </div>
  </div>

  <%end%>
  <%else%>
  <div id="articles">
    <div class="container d-flex"> 
      <div class="row my-2 mx-2 mt-5">
        <%= render @articles %>
      </div>
    </div>
  </div>
<%end%> 
<div id="more_articles">
<div class="news-more__wrapper">
  <div class="news-more__control">
    <%= link_to "Загрузить ещё", articles_by_category_path(page: @articles.next_page), remote: true,  class: "button-style button-style_expletive button-style_big news-more__button js-show-more-news text-secondary" %>
    </div>
  </div>
</div>
</div>

app/views/articles/_wide_article.html.erb
<div class="custom-col-6 mb-2">  
<div class="vertical_gray_line">
  <div class="card border-0 mr-3 ml-2">   
    <a href="<%= article_path(article.id)%>">
      <img class="card-img-top mr-2" src="<%= rails_blob_url(article.image) %>" height="250">
    </a>
    <div class="card-body">  
      <div class="row">
       <div class="col-md-6">
          <div class="news-tidings__subtitle">
            <h5 class="card-title"><b><a><%= link_to "#{article.title}", article_path(article.id)%></b></a></h5>
          </div>
          <%= render partial: "comment_and_date",object: article, as: 'article'%>
        </div>  
        <div class="col-md-6">
          <div class="news-tidings__speech news-helpers_hide_mobile-small">
            <div class="card-text"><%= simple_format(article.text.truncate(240)) %></div>
          </div>
        </div>
      </div>  
    </div>
  </div>
</div>
</div>

app/views/articles/index.html.erb
<div class="l-gradient-wrapper">
<%= render partial: "layouts/navigation"%>
  <div class="g-middle">
    <div class="g-middle-i">
    <%= render partial: "layouts/navigation_menu"%>
    <%if params[:category] == "all"%>
    <%= render partial: "all_news"%>
    <%else%>
    <%= render partial: "news_to_category"%>
    <%end%>
  </div>
</div>
</div>
<%= render partial: "layouts/footer"%>

app/views/articles/index.js.erb
$("#articles").append('<%= escape_javascript(render 'articles/article_more', collection: @articles)%>');
$("#more_articles").html('<%= escape_javascript(link_to "Загрузить ещё", articles_by_category_path(page: @articles.next_page), remote: true,  class: "button-style button-style_expletive button-style_big news-more__button js-show-more-news text-secondary") if @articles.next_page %>');

app/views/articles/search.html.erb
<div class="l-gradient-wrapper">
<%= render partial: "layouts/navigation"%>
  <div class="g-middle">
    <div class="g-middle-i">
      <%= render partial: "layouts/navigation_menu"%>
      <div id="search-results">
        <%= render partial: 'search_results' %>
      </div>
    <% if @articles.empty? %>
      <h4 align="center"><%= flash[:error]%></h4>
    <% end %>
    <% if @articles.size < 5 %>
      <div class="empty-place"> </div>
    <%end%>
    </div>
  </div>
</div>
<%= render partial: "layouts/footer"%>

app/views/articles/show.html.erb
<div class="l-gradient-wrapper">
<%= render partial: "layouts/navigation"%>
<% @user = current_user %>
<div class="g-middle">
    <div class="g-middle-i">
    <%= render partial: "layouts/navigation_menu"%>
    <div class="news-wrapper">
      <div class="news-posts">
      <div class="news-header news-header_extended">
        <div class="news-header__preview">
            <div class = "news-header__image">
              <img src="<%= rails_blob_url(@article.image) %>" width="100%">
              <div class="news-header__bottom">
                <div class="news-header__detail news-header__detail_position_left">
                  <div class="news-header__flex">
                    <div class="news-header__part news-header__part_1">
                      <div class="news-header__control">
                        <a href="#comments" class="button-style button-style_adscititious button-style_small news-header__button news-header__button_comments" id="news-header-comments-counter"><%= @article.comments.count%></a>
                        <div class="news-header__time">
                        <%= @article.parse_date %>
                        </div>
                      </div>
                    </div>
                    <div class="news-header__part news-header__part_2">
                    <div class="news-header__author news-helpers_hide_mobile">
                    <% author = User.find(@article.admin_id) %>
                    <% unless author.nil? %>
                      Автор: <%= author.first_name%>  <%= author.last_name %>
                    <% end %>
                    </div>
                    </div>
                  </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
      <div class="news-text">
        <div class="news-header__title">
          <h1 align="center"><%= @article.title %></h1>
        </div>
            <p><%= simple_format(@article.text)%></p>
        </div>
        <div class="row">
        <div class="col-md-6 offset-md-3">
          <% if @user && @user.type == "Admin"%>
            <div class="row mb-5">
              <%= button_to "Редактировать статью", {:controller => :articles, :action => 'edit', :id => @article.id }, 
              :method => :get , :class => "auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full" %>
            </div>
          <%end%>
        </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-4 ml-5">
            <div class="discussion">
              <h2 align="center" style="font-weight: bolder">Обсуждение</h2>
            </div>
          </div>
        </div>
        <% if @user%>
          <div class = "row">
            <div class="col-md-7 offset-md-1 mb-3">
              <div class="horisontal_gray_line" style="padding-left: 25px"></div>
            </div>
          </div>
          <div class = "row">
            <div class="comment-form-background">
              <div class="col-md-10 offset-md-1 my-3">
                <div class="comment-form">
                  <div class="row">
                    <div class="column">
                      <%= link_to image_tag("noavatar.png",class: "img-fluid rounded-circle"), 
                      controller: "users", action: "show", id: @user.id %>
                    </div>
                    <div class="column2">
                      <%= form_for :comment, url: "/articles/#{@article.id}/comments/", method: :post do |f| %>
                      <%  invalid = alert if alert %>
                        <%= f.hidden_field :article_id,  value: @article.id %>
                        <%= f.text_area :content,class: "form-control #{'is-invalid' if invalid}" , placeholder: "Ваше мнение, #{@user.id}?" %><br/>
                          
                    <% if alert == 'Комментарий не может быть пустым'%>
                      <div class="invalid-feedback d-block">
                        <p><big> <%= alert %></big></p> 
                      </div>
                    <%end%>
                        <div class="col-md-4">
                          <%= f.submit "Высказаться" , :class => "auth-button auth-button_primary auth-button_middle auth-form__button auth-form__button_width_full" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <%end%>
        <div class = "row">
            <div class="col-md-8 offset-md-1 my-3">
              <% @article.comments.each do |comment| %>
                <%= render partial: "comment", object: comment %> 
             <% end %>
            </div>
        </div>
        <div class="row">
        </div>
      </div>
</div>
</div>
</div>
</div>
<%= render partial: "layouts/footer"%>