config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: [:index, :edit, :update] 
  put '/make_admin/:id' , to:'users#make_admin'
  put '/cancel_admin/:id' , to:'users#cancel_admin_rights'
  get '/users/:id' , to:'users#show'
  get '/news/:category', to:'articles#index', as: 'articles_by_category'
  root :to => "articles#index", :category => 'all'
  post '/preferences' , to: 'preferences#create', as: 'preference_create'
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  get '/search' => 'articles#search', :as => 'search_article'
end

app/views/layouts/_footer.html.erb
<footer class="g-bottom">
    <div class="g-bottom-i">
        <div class="footer-style">
    <div class="footer-style__flex">
        <div class="footer-style__part footer-style__part_1">
            <ul class="footer-style__list">
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        О компании
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Контакты редакции
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_additional">
                        Реклама
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_additional">
                        Размещение в каталоге
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Вакансии
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Манифест
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Пользовательское соглашение
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Публичные договоры
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Политика конфиденциальности
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Поддержка пользователей
                    </a>
                </li>
                <li class="footer-style__item">
                    <a href="" class="footer-style__link footer-style__link_primary">
                        Правила возврата
                    </a>
                </li>
            </ul>
        </div>
        <div class="footer-style__part footer-style__part_2">
            <div class="footer-style__copy">
                © 2001—2021 Onliner.by
            </div>
        </div>
    </div>
</div>
    </div>
    <!--/Footer-->
</footer>

app/views/layouts/_footerlogin.html.erb
<div class="auth-form__description auth-form__description_other auth-form__description_small auth-form__description_condensed">
© 2001–2021 Onliner
</div>

app/views/layouts/_navigation.html.erb
<header class="g-top">
  <div class="b-top-menu">
    <div class="g-top-i">
      <nav class="b-top-navigation">
        <ul class="b-main-navigation">
          <li class="b-main-navigation__item">
            <a href="" class="b-main-navigation__advert b-main-navigation__advert_primary">
              <div class="b-main-navigation__bubble b-main-navigation__bubble_primary">
                Все суперцены
              </div>
            </a>
            <a href="" class="b-main-navigation__link">
              <span class="b-main-navigation__text">Каталог</span>
            </a>
          </li>
          <li class="b-main-navigation__item b-main-navigation__item_arrow">
            <div class="dropdown">
              <a href="<%= root_path%>" class="b-main-navigation__link "  id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false>
              <a href="" class="dropdown-toggle" data-toggle="dropdown">Новости <span class="caret"></span></a>
              </a>
              <ul class="dropdown-menu" role="menu">
              <div class = "container">
              <div class ="row my-4">
              <div class="g-top-i">
                <div class="b-main-navigation__dropdown-wrapper">
                  <div class="b-main-navigation__dropdown-grid">
                    <div class="b-main-navigation__dropdown-column b-main-navigation__dropdown-column_25">
                      <div class="b-main-navigation__dropdown-title">
                        <a href="/news/people" class="b-main-navigation__dropdown-title-link">Люди</a>
                      </div>
                      
                      <ul class="b-main-navigation__dropdown-news-list" style="padding-left: 0;">
                      <% @articles_navbar[0][0..2].each do |article|%>
                        <li class="b-main-navigation__dropdown-news-item">
                          <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-preview">
                          <img  src="<%= rails_blob_url(article.image) %>"width="90" height="60">
                          </a>
                          <div class="b-main-navigation__dropdown-news-description" style="overflow-wrap: break-word;">
                            <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-link"><%= article.title%></a>
                          </div>
                        </li>
                      <% end %>
                      </ul>
                      <div class="b-main-navigation__dropdown-control">
                          <a href="/news/people" class="b-main-navigation__dropdown-button">
                                          Перейти в раздел
                                  </a>
                      </div>
                    </div>
                      <div class="b-main-navigation__dropdown-column b-main-navigation__dropdown-column_25">
                        <div class="b-main-navigation__dropdown-title">
                          <a href="/news/auto" class="b-main-navigation__dropdown-title-link">Авто</a>
                        </div>
                        <ul class="b-main-navigation__dropdown-news-list" style="padding-left: 0;">
                        <% @articles_navbar[2][0..2].each do |article|%>
                          <li class="b-main-navigation__dropdown-news-item">
                            <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-preview">
                            <img  src="<%= rails_blob_url(article.image) %>"width="90" height="60">
                            </a>
                            <div class="b-main-navigation__dropdown-news-description" style="overflow-wrap: break-word;">
                              <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-link"><%= article.title%></a>
                            </div>
                          </li>
                          <% end %>
                        </ul>
                        <div class="b-main-navigation__dropdown-control">
                          <a href="/news/auto" class="b-main-navigation__dropdown-button">
                            Перейти в раздел
                          </a>
                        </div>  
                      </div>
                    <div class="b-main-navigation__dropdown-column b-main-navigation__dropdown-column_25">
                      <div class="b-main-navigation__dropdown-title">
                        <a href="/news/technologies" class="b-main-navigation__dropdown-title-link">Технологии</a>
                      </div>
                      <ul class="b-main-navigation__dropdown-news-list" style="padding-left: 0;">
                      <% @articles_navbar[3][0..2].each do |article|%>
                        <li class="b-main-navigation__dropdown-news-item">
                          <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-preview">
                          <img  src="<%= rails_blob_url(article.image) %>"width="90" height="60">
                
                          </a>
                          <div class="b-main-navigation__dropdown-news-description" style="overflow-wrap: break-word;">
                            <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-link"><%= article.title%></a>
                          </div>
                        </li>
                        <%end%>
                      </ul>
                    <div class="b-main-navigation__dropdown-control">
                      <a href="/news/technologies" class="b-main-navigation__dropdown-button">
                        Перейти в раздел
                      </a>
                    </div>
                  </div>
                  <div class="b-main-navigation__dropdown-column b-main-navigation__dropdown-column_25">
                    <div class="b-main-navigation__dropdown-title">
                      <a href="/news/realt" class="b-main-navigation__dropdown-title-link">Недвижимость</a>
                    </div>
                     <ul class="b-main-navigation__dropdown-news-list" style="padding-left: 0;">
                     <% @articles_navbar[4][0..2].each do |article|%>
                      <li class="b-main-navigation__dropdown-news-item">
                        <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-preview">
                        <img  src="<%= rails_blob_url(article.image) %>"width="90" height="60">
                        </a>
                        <div class="b-main-navigation__dropdown-news-description" style="overflow-wrap: break-word;">
                            <a href="<%= article_path(article.id)%>" class="b-main-navigation__dropdown-news-link"><%= article.title%></a>
                        </div>
                      </li>
                      <%end%>
                    </ul>
                    <div class="b-main-navigation__dropdown-control">
                      <a href="/news/realt" class="b-main-navigation__dropdown-button">Перейти в раздел</a>
                    </div>
                  </div>
                </div>
              </div>
              </div>
              </div>
            </div>

          </ul>
          </div>
            
          </li>
          <li class="b-main-navigation__item b-main-navigation__item_arrow">
            <a href="" target="_blank" class="b-main-navigation__advert b-main-navigation__advert_additional">
              <div class="b-main-navigation__bubble b-main-navigation__bubble_additional">
                Выиграйте iPhone 12
              </div>
              </a>
              <a href="" class="b-main-navigation__link">
                <span class="b-main-navigation__text">Автобарахолка</span>
              </a>
          </li>
          <li class="b-main-navigation__item b-main-navigation__item_arrow">
              <a href="" class="b-main-navigation__link">
                  <span class="b-main-navigation__text">Дома и квартиры</span>
              </a>
          </li>
          <li class="b-main-navigation__item">
              <a href="" class="b-main-navigation__link">
                  <span class="b-main-navigation__text">Услуги</span>
              </a>
          </li>

          <li class="b-main-navigation__item">
              <a href="" class="b-main-navigation__link">
                  <span class="b-main-navigation__text">Барахолка</span>
              </a>
          </li>
          <li class="b-main-navigation__item">
              <a href="" class="b-main-navigation__link">
                  <span class="b-main-navigation__text">Форум</span>
              </a>
          </li>
        </ul>
        <a href="https://clever.onliner.by/?utm_source=onliner&utm_medium=navigation&utm_campaign=clever" target="_blank" class="b-top-navigation-clover">Onliner Клевер</a>
        <div class="b-top-navigation-age">18+</div>
      </nav>
    </div>
  </div>
  <div class="b-top-actions">
    <div class="g-top-i">
    <div class ="container">
    <div class = "row"> 
      <div class ="col-md-2">
        <div class="b-top-logo">
          <a href="<%=root_path %>">
            <img srcset="https://gc.onliner.by/images/logo/onliner_logo.v3.png?token=1617371555,
                        https://gc.onliner.by/images/logo/onliner_logo.v3@2x.png?token=1617371555 2x"
            src="https://gc.onliner.by/images/logo/onliner_logo.v3@2x.png?token=1617371555" width="180" height="40" alt="Onliner" class="onliner_logo">
          </a>
        </div>
      </div>
      <div class ="col-md-8 pt-2">
        <div class="b-top-wrapper">                 
        <div id="fast-search" class="fast-search">
                <%= form_tag(search_article_path, method: 'get') do %>
                <%= text_field_tag(:search, params[:search], :class => "form-control",:type =>"text", :placeholder =>"Поиск")%>
                <% end %>
            <input type="hidden" name="charset" value="utf-8">
        </div>
      </div>
      </div>
      <div class ="col-md-2 pt-2">
        <div id="userbar" class="b-top-profile">
          <% if user_logged_in? %>
            <div class="b-top-profile__image js-header-user-avatar mr-3">
              <% if current_user.photo.attached? %>
                <%= link_to image_tag(current_user.photo, class: "rounded-circle" ,:alt => "Cinque Terre", size: "71" ),controller: "users", action: "show", id: current_user.id %>
              <% else %>
                <%= link_to image_tag("noavatar.png",class: "img-fluid rounded-circle"), controller: "users", action: "show", id: current_user.id %>
              <% end %>
            </div>
            <div class="auth-bar auth-bar--top mt-2" data-bind="visible: false" style="">
              <a href="<%=logout_path%>" class="auth-bar__item auth-bar__item--text"  style="height: 40px">Выход</a>
            </div>
          <% else %>
            <div class="auth-bar auth-bar--top mt-2" data-bind="visible: false" style="">
              <a href="<%=login_path%>" class="auth-bar__item auth-bar__item--text"  style="height: 40px">Вход</a>
            </div>
          <% end %>
          </div>
          </div>
        </div>
      </div>
      </div> 
      </div>
    </div>        
    </div>   
  </div>
</header>

app/views/layouts/_navigation_menu.html.erb
<div class="sticky-top">
<div id="project-navigation" class="project-navigation project-navigation_overflow project-navigation_nocap project-navigation_scroll" 
                        style="width: 1380px; height: 50px; left: 0px; top: 0px;">
    <div class="project-navigation__flex">
        <div class="project-navigation__part project-navigation__part_1">
            <ul class="project-navigation__list project-navigation__list_primary">
               <li class="project-navigation__item project-navigation__item_primary <%='project-navigation__item_active' if params[:category]=='people'%>">
                  <a href="/news/people" class="project-navigation__link project-navigation__link_primary">
                    <span class="project-navigation__text">
                      <span class="project-navigation__sign">Люди</span>
                    </span>
                  </a>
                </li>
                <li class="project-navigation__item project-navigation__item_primary <%='project-navigation__item_active' if params[:category]=='opinions'%>">
                  <a href="/news/opinions" class="project-navigation__link project-navigation__link_primary">
                    <span class="project-navigation__text">
                      <span class="project-navigation__sign">Мнения</span>
                    </span>
                  </a>
                </li>
                <li class="project-navigation__item project-navigation__item_primary <%='project-navigation__item_active' if params[:category]=='auto'%> ">
                  <a href="/news/auto" class="project-navigation__link project-navigation__link_primary">
                    <span class="project-navigation__text">
                      <span class="project-navigation__sign">Авто</span>
                    </span>
                  </a>
                </li>
                <li class="project-navigation__item project-navigation__item_primary <%='project-navigation__item_active' if params[:category]=='technologies'%> ">
                  <a href="/news/technologies" class="project-navigation__link project-navigation__link_primary">
                    <span class="project-navigation__text">
                      <span class="project-navigation__sign">Технологии</span>
                    </span>
                  </a>
                </li>
                <li class="project-navigation__item project-navigation__item_primary <%='project-navigation__item_active' if params[:category]=='realt'%> ">
                  <a href="/news/realt" class="project-navigation__link project-navigation__link_primary">
                    <span class="project-navigation__text">
                      <span class="project-navigation__sign">Недвижимость</span>
                    </span>
                  </a>
                </li>
                <%if current_user && current_user.type == "Admin"%>
                  <li class="project-navigation__item project-navigation__item_primary ">
                    <a href="<%=users_path %>" class="project-navigation__link project-navigation__link_primary">
                      <span class="project-navigation__text">
                        <span class="project-navigation__sign">Пользователи</span>
                      </span>
                    </a>
                  </li>

                  <li class="project-navigation__item project-navigation__item_primary ">
                  <a href="/articles/new" class="project-navigation__link project-navigation__link_primary">
                    <span class="project-navigation__text">
                      <span class="project-navigation__sign">Добавить новость</span>
                    </span>
                  </a>
                </li>
                <%end%>  
              </ul>
            </div>
    </div>
</div>
</div>

app/views/layouts/_notification.html.erb
<div class ="container">
  <% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="notice">
      <h6 class="notice" align="center"><%= notice %></h6>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="notice">
      <h6 class="notice" align="left"><%= alert %></h6>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteClone</title>
    <meta charset="utf-8">
    <meta name="theme-color" content="#246eb7">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Onliner</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="shortcut icon" href="https://gc.onliner.by/favicon.ico">
    <%= stylesheet_link_tag "tech.min" %>
    <%= stylesheet_link_tag "app.min" %>
    <%= stylesheet_link_tag "common.min" %>
    <%= stylesheet_link_tag "auth.min" %>
    <%= stylesheet_link_tag "non-critical.min" %>
    <%= stylesheet_link_tag "responsive_layout.min" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="alternate" type="application/rss+xml" title="Onliner" href="/feed"><meta name="yandex-verification" content="64023db300b691cc" />  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@700&display=swap">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <style>
    .dropdown {
        position: static !important;
    }
      
    .dropdown-menu {
        box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15)!important;
        margin-top: 0px !important;
        width: 100% !important;
    }
</style>
    </head>

  <body>
    <%= yield %>
  </body>

  
</html>